### ISSUE TITLE
*.gz instead of *.bin

### ISSUE THREAD

**Issue by lesharodin** [ExpressLRS/web-flasher#25] opened 2024-01-14 08:46 UTC
Web flasher outputs uncomressed .bin file, that not suitable for wifi reciever upgrade (not enough space)
Need to output compressed .gz firmware, like desktop configurator does.

**Comment by CapnBry** [comment] 2024-06-04 12:30
I was just noticing that too. As a workaround I just used [Online GZIP de/compressor](https://gzip.swimburger.net/) using Compress / Optimal to gzip it before uploading to an RX.

I believe the issue is that the web flasher doesn't know which firmwares need to be compressed and which do not? If you're flashing over wifi, then all _can_ be compressed, but for UART / Betaflight passthrough they have to be uncompressed. I feel like direct download from the web flasher should always be compressed but I am not fully aware of all the intricacies of why some are compressed and some aren't.

**Comment by pkendall64** [comment] 2024-07-06 20:07
Closing as this is done now.

**Closed by pkendall64** 2024-07-06 20:07 UTC
